name: .NET 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for Version tag in HEAD
      run: |
        version="$(git describe --abbrev=0 --match="[0-9]*.[0-9]*.[0-9]*" --candidates 0 @ || echo "not found")"
        if [[ $version == 'not found' ]]
        then 
          exit 1
        fi
        echo "VERSION=${version}" >> $GITHUB_ENV
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
          dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build -l "console;verbosity=detailed" --logger trx --results-directory "TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: TestResults
      if: ${{ always() }}
    - name: Publish Package
      run: dotnet pack src/main/DebugLogger/DebugLogger.csproj -c Release -o out /p:Version=${VERSION}
